import type { Quiz } from "./types";

export const QUIZZES: Quiz[] = [
  {
    slug: "q-m0",
    title: "Quiz · Tổng quan EMAS",
    pass: 70,
    questions: [
      {
        id: "m0q1",
        type: "single",
        prompt: "Hệ thống EMAS chấm mỗi cuộc gọi theo thang điểm nào?",
        options: [
          { key: "a", text: "100 điểm / 5 nhóm" },
          { key: "b", text: "40 điểm / 4 nhóm" },
          { key: "c", text: "10 điểm / 1 nhóm" },
          { key: "d", text: "20 điểm / 2 nhóm" },
        ],
        correct: ["b"],
        explain: "40 điểm, 4 nhóm tiêu chí (1.x–4.x), mỗi nhóm tối đa 10 điểm.",
      },
      {
        id: "m0q2",
        type: "multi",
        prompt: "Hai lỗi nào CÓ TRỪ ĐIỂM (ảnh hưởng trực tiếp KPI)?",
        options: [
          { key: "a", text: "Chẩn đoán lỗi (1.2.1)" },
          { key: "b", text: "Chào hỏi khách hàng" },
          { key: "c", text: "Xin lỗi/Cảm ơn khi chờ máy (4.4)" },
          { key: "d", text: "Cảm ơn cuối cuộc gọi" },
        ],
        correct: ["a", "c"],
        explain: "1.2.1 và 4.4 là lỗi CÓ TRỪ ĐIỂM. Chào hỏi & cảm ơn cuối cuộc chỉ \"nhắc nhở\".",
      },
      {
        id: "m0q3",
        type: "boolean",
        prompt: "Cuộc gọi dài có trạng thái \"Không hài lòng\" sẽ bị hệ thống rà soát kỹ hơn.",
        options: [
          { key: "t", text: "Đúng" },
          { key: "f", text: "Sai" },
        ],
        correct: ["t"],
        explain: "Đúng. Cuộc dài + \"Không hài lòng\" + âm lượng gay gắt là nhóm bị \"soi\" kỹ.",
      },
    ],
  },
  {
    slug: "q-m1",
    title: "Quiz · Nhận diện lỗi",
    pass: 70,
    questions: [
      {
        id: "m1q1",
        type: "single",
        prompt: "Hành vi nào là lỗi Tuân thủ Nghiệp vụ (1.x)?",
        options: [
          { key: "a", text: "Chủ động tra cứu hệ thống nội bộ" },
          { key: "b", text: "Đẩy KH sang \"các bạn Sale\" mà không kiểm tra trước" },
          { key: "c", text: "Xác định đúng loại lỗi rồi hướng dẫn" },
          { key: "d", text: "Hẹn thời gian phản hồi cụ thể" },
        ],
        correct: ["b"],
        explain: "Đẩy trách nhiệm sang Sale/Kinh doanh mà không chủ động tra cứu là lỗi điểm nóng nhóm 1.x.",
      },
      {
        id: "m1q2",
        type: "single",
        prompt: "KH gọi 3–4 lần, ĐTV hứa gọi lại nhưng không ai liên hệ. Đây là lỗi nhóm nào?",
        options: [
          { key: "a", text: "Nhóm 1.x – Nghiệp vụ" },
          { key: "b", text: "Nhóm 2.x – Thái độ" },
          { key: "c", text: "Nhóm 3.x – Trách nhiệm" },
          { key: "d", text: "Nhóm 4.x – Giao tiếp" },
        ],
        correct: ["c"],
        explain: "Thất hứa liên hệ lại là lỗi Tinh thần Trách nhiệm (3.x), gây mất niềm tin nghiêm trọng.",
      },
      {
        id: "m1q3",
        type: "multi",
        prompt: "Dấu hiệu nào khiến cuộc gọi bị EMAS đánh giá thấp?",
        options: [
          { key: "a", text: "Âm lượng cao giọng/gay gắt" },
          { key: "b", text: "Cuộc dài >3–4 phút chỉ \"xin lỗi\" và \"xin chờ\", không kết quả" },
          { key: "c", text: "Tra cứu nhanh và chốt hướng xử lý" },
          { key: "d", text: "Hỏi lặp lại thông tin KH đã cung cấp" },
        ],
        correct: ["a", "b", "d"],
        explain: "Cao giọng, cuộc dài không kết quả, hỏi lặp lại đều là dấu hiệu xấu. Tra cứu nhanh & chốt hướng là tốt.",
      },
    ],
  },
  {
    slug: "q-m2",
    title: "Quiz · Mẫu câu ghi điểm",
    pass: 70,
    questions: [
      {
        id: "m2q1",
        type: "single",
        prompt: "Cụm từ nào giúp máy ghi nhận sự ĐỒNG CẢM (4.1)?",
        options: [
          { key: "a", text: "\"Anh chờ chút\"" },
          { key: "b", text: "\"Em hiểu ạ, em rất tiếc về sự cố…\"" },
          { key: "c", text: "\"Cái này không phải của em\"" },
          { key: "d", text: "\"Anh tự kiểm tra lại đi\"" },
        ],
        correct: ["b"],
        explain: "\"Em hiểu\", \"em rất tiếc\" là cụm từ ghi điểm đồng cảm.",
      },
      {
        id: "m2q2",
        type: "single",
        prompt: "Khi cần chuyển tuyến/hẹn trả lời (1.2.5), điều BẮT BUỘC phải có là gì?",
        options: [
          { key: "a", text: "Hẹn thời gian + dự kiến xử lý rõ ràng" },
          { key: "b", text: "Chỉ cần nói \"em chuyển bộ phận khác\"" },
          { key: "c", text: "Bảo KH tự liên hệ Sale" },
          { key: "d", text: "Cúp máy nhanh để giảm thời lượng" },
        ],
        correct: ["a"],
        explain: "Phải có \"hẹn thời gian\" + \"thông báo rõ dự kiến\" để không bị trừ điểm khi chưa xử lý ngay.",
      },
      {
        id: "m2q3",
        type: "boolean",
        prompt: "Với 18001260, khi xác định nhu cầu cần NÊU RÕ loại lỗi KH gặp để đạt điểm tối đa tiêu chí nghiệp vụ.",
        options: [
          { key: "t", text: "Đúng" },
          { key: "f", text: "Sai" },
        ],
        correct: ["t"],
        explain: "Đúng — nêu rõ loại lỗi (thao tác/phần mềm) là yêu cầu riêng để đạt điểm 1.2.1.",
      },
    ],
  },
  {
    slug: "q-m3",
    title: "Quiz · Phục vụ Doanh nghiệp",
    pass: 70,
    questions: [
      {
        id: "m3q1",
        type: "single",
        prompt: "Công thức T.I.Ề.N viết tắt cho điều gì?",
        options: [
          { key: "a", text: "Thời gian – Ích lợi – Êm đẹp – Ngắn gọn" },
          { key: "b", text: "Tiền – Ít – Êm – Nhanh" },
          { key: "c", text: "Tốc độ – Im lặng – Êm – Nói" },
          { key: "d", text: "Thân thiện – Ích lợi – Êm – Nhẹ" },
        ],
        correct: ["a"],
        explain: "T.I.Ề.N = Thời gian – Ích lợi – Êm đẹp – Ngắn gọn.",
      },
      {
        id: "m3q2",
        type: "single",
        prompt: "\"4 HỎI (60 giây)\" KHÔNG bao gồm câu hỏi nào?",
        options: [
          { key: "a", text: "Hỏi dịch vụ gì" },
          { key: "b", text: "Hỏi ai dùng" },
          { key: "c", text: "Hỏi số CMND/CCCD của KH" },
          { key: "d", text: "Hỏi cần hỗ trợ gì" },
        ],
        correct: ["c"],
        explain: "4 HỎI = Dịch vụ gì / Ai dùng / Dùng ở đâu / Cần hỗ trợ gì.",
      },
      {
        id: "m3q3",
        type: "single",
        prompt: "Khi KH căng thẳng, áp dụng công thức nào?",
        options: [
          { key: "a", text: "RÕ – ĐÚNG – AN TOÀN" },
          { key: "b", text: "NGHE – NÓI – DẪN – CHỐT" },
          { key: "c", text: "T.I.Ề.N" },
          { key: "d", text: "3R" },
        ],
        correct: ["b"],
        explain: "NGHE – NÓI – DẪN – CHỐT: Nghe cho đủ – Nói cho rõ – Dẫn cho đúng – Chốt cho an.",
      },
    ],
  },
  {
    slug: "q-m4",
    title: "Quiz · Tư vấn IB",
    pass: 70,
    questions: [
      {
        id: "m4q1",
        type: "single",
        prompt: "Lỗi lặp lại lớn nhất ở cuộc IB tư vấn là gì?",
        options: [
          { key: "a", text: "Tư vấn quá kỹ làm KH chán" },
          { key: "b", text: "Thụ động, chỉ ghi nhận thông tin rồi chuyển địa bàn, không tư vấn" },
          { key: "c", text: "Nói quá nhiều về giá" },
          { key: "d", text: "Gọi lại KH quá nhiều lần" },
        ],
        correct: ["b"],
        explain: "ĐTV thụ động như \"máy ghi âm\" — chỉ xin thông tin chuyển địa bàn, không tư vấn sơ khởi.",
      },
      {
        id: "m4q2",
        type: "multi",
        prompt: "Probing Skills gồm khai thác những thông tin nào trước khi chuyển?",
        options: [
          { key: "a", text: "Quy mô" },
          { key: "b", text: "Mục đích sử dụng" },
          { key: "c", text: "Hiện trạng (đã có gì chưa)" },
          { key: "d", text: "Mức độ gấp" },
        ],
        correct: ["a", "b", "c", "d"],
        explain: "Tất cả: quy mô, mục đích, hiện trạng, mức độ gấp.",
      },
      {
        id: "m4q3",
        type: "single",
        prompt: "Bước CUỐI trong khung kịch bản tư vấn chuẩn là gì?",
        options: [
          { key: "a", text: "Khai thác thông tin" },
          { key: "b", text: "Cung cấp thông tin cơ bản" },
          { key: "c", text: "Xác nhận nhu cầu" },
          { key: "d", text: "Chuyển địa bàn (sau khi KH đã nắm cơ bản)" },
        ],
        correct: ["d"],
        explain: "Thứ tự: Khai thác → Cung cấp → Nhận diện → Xác nhận → Chuyển địa bàn.",
      },
    ],
  },
  {
    slug: "q-m5",
    title: "Quiz · Kiến thức Dịch vụ",
    pass: 70,
    questions: [
      {
        id: "m5q1",
        type: "single",
        prompt: "Đầu số nào MIỄN PHÍ cho người gọi (DN trả cước)?",
        options: [
          { key: "a", text: "1900" },
          { key: "b", text: "1800" },
          { key: "c", text: "Cả hai" },
          { key: "d", text: "Không số nào" },
        ],
        correct: ["b"],
        explain: "1800 miễn phí người gọi (DN trả cước); 1900 người gọi trả phí.",
      },
      {
        id: "m5q2",
        type: "single",
        prompt: "KH cần tổng đài nội bộ để bấm số đổ về chi nhánh — nên tư vấn dịch vụ nào?",
        options: [
          { key: "a", text: "SMS Brandname" },
          { key: "b", text: "VCC (Tổng đài ảo)" },
          { key: "c", text: "Voice Brandname" },
          { key: "d", text: "Loa thông báo thanh toán" },
        ],
        correct: ["b"],
        explain: "VCC là tổng đài ảo: phân nhánh, định tuyến nội bộ, ghi âm.",
      },
      {
        id: "m5q3",
        type: "single",
        prompt: "KH muốn gửi tin nhắn hiển thị TÊN thương hiệu thay số điện thoại?",
        options: [
          { key: "a", text: "SMS Brandname" },
          { key: "b", text: "Sip Trunking" },
          { key: "c", text: "eContract" },
          { key: "d", text: "1900" },
        ],
        correct: ["a"],
        explain: "SMS Brandname = tin nhắn hiển thị tên thương hiệu.",
      },
    ],
  },
  {
    slug: "q-m6",
    title: "Quiz · Xử lý từ chối",
    pass: 70,
    questions: [
      {
        id: "m6q1",
        type: "single",
        prompt: "Khi KH chê \"giá cao quá\", cách xử lý tốt nhất là?",
        options: [
          { key: "a", text: "Tranh luận chứng minh giá không cao" },
          { key: "b", text: "Đồng cảm + quy đổi giá trị + trao lựa chọn gói phù hợp" },
          { key: "c", text: "Giảm giá ngay lập tức" },
          { key: "d", text: "Bảo KH tự cân nhắc rồi cúp máy" },
        ],
        correct: ["b"],
        explain: "Không tranh luận; đồng cảm, quy về lợi ích, cho KH lựa chọn gói.",
      },
      {
        id: "m6q2",
        type: "single",
        prompt: "\"Đơn giản hóa thông tin kỹ thuật\" nghĩa là gì?",
        options: [
          { key: "a", text: "Nói thật nhiều thuật ngữ cho chuyên nghiệp" },
          { key: "b", text: "Chuyển ngôn ngữ tính năng → lợi ích thực tế cho DN" },
          { key: "c", text: "Bỏ qua không giải thích" },
          { key: "d", text: "Đọc nguyên tài liệu kỹ thuật" },
        ],
        correct: ["b"],
        explain: "Chuyển tính năng khô khan thành lợi ích KH hiểu được.",
      },
    ],
  },
];

export const quizBySlug = (slug: string) => QUIZZES.find((q) => q.slug === slug);

export const FINAL_QUIZ: Quiz = {
  slug: "final",
  title: "Bài kiểm tra cuối khóa",
  pass: 80,
  questions: [
    {
      id: "f1",
      type: "single",
      prompt: "Thang điểm EMAS mỗi cuộc gọi?",
      options: [
        { key: "a", text: "40 điểm / 4 nhóm" },
        { key: "b", text: "100 điểm" },
        { key: "c", text: "10 điểm" },
        { key: "d", text: "50 điểm / 5 nhóm" },
      ],
      correct: ["a"],
      explain: "40 điểm, 4 nhóm tiêu chí.",
    },
    {
      id: "f2",
      type: "multi",
      prompt: "Hai lỗi CÓ TRỪ ĐIỂM cần nhớ?",
      options: [
        { key: "a", text: "Chẩn đoán lỗi (1.2.1)" },
        { key: "b", text: "Xin lỗi/Cảm ơn khi chờ máy (4.4)" },
        { key: "c", text: "Chào hỏi đầu cuộc" },
        { key: "d", text: "Cảm ơn cuối cuộc" },
      ],
      correct: ["a", "b"],
      explain: "1.2.1 và 4.4 bị trừ điểm; chào hỏi/cảm ơn chỉ nhắc nhở.",
    },
    {
      id: "f3",
      type: "single",
      prompt: "Lỗi lặp lại lớn nhất ở cuộc IB tư vấn?",
      options: [
        { key: "a", text: "Tư vấn quá kỹ" },
        { key: "b", text: "Chỉ ghi nhận thông tin rồi chuyển địa bàn, không tư vấn" },
        { key: "c", text: "Nói nhiều về giá" },
        { key: "d", text: "Gọi lại quá nhiều" },
      ],
      correct: ["b"],
      explain: "Thụ động, không tư vấn sơ khởi dù KH có nhu cầu rõ.",
    },
    {
      id: "f4",
      type: "single",
      prompt: "Thứ tự đúng của khung kịch bản tư vấn chuẩn?",
      options: [
        { key: "a", text: "Chuyển địa bàn → khai thác → xác nhận" },
        { key: "b", text: "Khai thác → cung cấp thông tin → nhận diện → xác nhận → chuyển địa bàn" },
        { key: "c", text: "Xác nhận → chuyển địa bàn → khai thác" },
        { key: "d", text: "Cung cấp giá → chốt đơn → chuyển" },
      ],
      correct: ["b"],
      explain: "Khai thác → Cung cấp → Nhận diện → Xác nhận → Chuyển địa bàn.",
    },
    {
      id: "f5",
      type: "single",
      prompt: "Đầu số 1800 đặc điểm gì?",
      options: [
        { key: "a", text: "Người gọi trả phí" },
        { key: "b", text: "Miễn phí người gọi, DN trả cước" },
        { key: "c", text: "Chỉ gọi nội bộ" },
        { key: "d", text: "Là tổng đài ảo" },
      ],
      correct: ["b"],
      explain: "1800 miễn phí cho người gọi; DN chịu cước — hợp CSKH.",
    },
    {
      id: "f6",
      type: "single",
      prompt: "KH cần nhiều kênh thoại đồng thời để nhận & gọi — tư vấn dịch vụ nào?",
      options: [
        { key: "a", text: "SMS Brandname" },
        { key: "b", text: "Sip Trunking" },
        { key: "c", text: "Loa thanh toán" },
        { key: "d", text: "eContract" },
      ],
      correct: ["b"],
      explain: "Sip Trunking = đường trung kế thoại, nhiều kênh đồng thời.",
    },
    {
      id: "f7",
      type: "single",
      prompt: "Khi KH căng thẳng, áp dụng công thức nào?",
      options: [
        { key: "a", text: "NGHE – NÓI – DẪN – CHỐT" },
        { key: "b", text: "3R" },
        { key: "c", text: "T.I.Ề.N" },
        { key: "d", text: "RÕ – ĐÚNG – AN TOÀN" },
      ],
      correct: ["a"],
      explain: "NGHE – NÓI – DẪN – CHỐT cho tình huống KH căng.",
    },
    {
      id: "f8",
      type: "single",
      prompt: "Khi cần hẹn trả lời (1.2.5), bắt buộc phải có?",
      options: [
        { key: "a", text: "Hẹn thời gian + dự kiến xử lý rõ ràng" },
        { key: "b", text: "Cúp máy nhanh" },
        { key: "c", text: "Bảo KH tự liên hệ Sale" },
        { key: "d", text: "Không cần gì thêm" },
      ],
      correct: ["a"],
      explain: "Phải hẹn thời gian + dự kiến rõ để không bị trừ điểm.",
    },
    {
      id: "f9",
      type: "boolean",
      prompt: "Khách có nhu cầu rõ ràng thì được phép chỉ xin SĐT rồi chuyển địa bàn ngay.",
      options: [
        { key: "t", text: "Đúng" },
        { key: "f", text: "Sai" },
      ],
      correct: ["f"],
      explain: "Sai. Phải khai thác + cung cấp thông tin cơ bản trước, rồi mới chuyển.",
    },
    {
      id: "f10",
      type: "single",
      prompt: "Mẫu câu xin hỗ trợ trực tiếp trên máy KH?",
      options: [
        { key: "a", text: "\"Anh tự sửa đi\"" },
        { key: "b", text: "\"Anh/Chị cho em xin Ultraviewer để hỗ trợ trực tiếp trên máy tính ạ.\"" },
        { key: "c", text: "\"Em không hỗ trợ từ xa được\"" },
        { key: "d", text: "\"Anh ra điểm giao dịch nhé\"" },
      ],
      correct: ["b"],
      explain: "Mẫu Ultraview bắt buộc khi cần hỗ trợ trực tiếp.",
    },
  ],
};
