import type { Quiz } from "./types";

export const QUIZZES: Quiz[] = [
  {
    slug: "q-m0",
    title: "Quiz · Chuẩn kỹ năng & Tư duy",
    pass: 70,
    questions: [
      {
        id: "m0q1",
        type: "multi",
        prompt: "4 trụ cột kỹ năng CSKH gồm những nhóm nào?",
        options: [
          { key: "a", text: "Nghiệp vụ" },
          { key: "b", text: "Thái độ" },
          { key: "c", text: "Trách nhiệm" },
          { key: "d", text: "Giao tiếp" },
        ],
        correct: ["a", "b", "c", "d"],
        explain: "Bốn trụ cột: Nghiệp vụ – Thái độ – Trách nhiệm – Giao tiếp.",
      },
      {
        id: "m0q2",
        type: "single",
        prompt: "Chuẩn phục vụ khách Doanh nghiệp gói gọn trong 3 chữ nào?",
        options: [
          { key: "a", text: "ĐÚNG – NHANH – RÕ" },
          { key: "b", text: "RẺ – NHANH – DỄ" },
          { key: "c", text: "VUI – NHANH – GỌN" },
          { key: "d", text: "ĐÚNG – ĐỦ – ĐẸP" },
        ],
        correct: ["a"],
        explain: "Khách DN cần ĐÚNG – NHANH – RÕ.",
      },
      {
        id: "m0q3",
        type: "single",
        prompt: "Công thức tư duy T.I.Ề.N viết tắt cho điều gì?",
        options: [
          { key: "a", text: "Thời gian – Ích lợi – Êm đẹp – Ngắn gọn" },
          { key: "b", text: "Tiền – Ít – Êm – Nhanh" },
          { key: "c", text: "Tốc độ – Im lặng – Êm – Nói" },
          { key: "d", text: "Thân thiện – Ích lợi – Êm – Nhẹ" },
        ],
        correct: ["a"],
        explain: "T.I.Ề.N = Thời gian – Ích lợi – Êm đẹp – Ngắn gọn.",
      },
    ],
  },
  {
    slug: "q-m1",
    title: "Quiz · Tiếp nhận & Chẩn đoán",
    pass: 70,
    questions: [
      {
        id: "m1q1",
        type: "single",
        prompt: "\"4 HỎI (60 giây)\" KHÔNG bao gồm câu hỏi nào?",
        options: [
          { key: "a", text: "Hỏi dịch vụ gì" },
          { key: "b", text: "Hỏi ai dùng" },
          { key: "c", text: "Hỏi số CMND/CCCD của khách" },
          { key: "d", text: "Hỏi cần hỗ trợ gì" },
        ],
        correct: ["c"],
        explain: "4 HỎI = Dịch vụ gì / Ai dùng / Dùng ở đâu / Cần hỗ trợ gì.",
      },
      {
        id: "m1q2",
        type: "single",
        prompt: "Khách bức xúc \"không ký được tờ khai\". Bước xử lý đúng đầu tiên?",
        options: [
          { key: "a", text: "Trấn an chung chung rồi hứa xử lý ngay cho khách yên tâm" },
          { key: "b", text: "Định khung: hỏi thông báo lỗi đang hiện gì, không ký được trên hệ thống nào, xin Ultraview" },
          { key: "c", text: "Chuyển ngay sang bộ phận khác cho nhanh" },
          { key: "d", text: "Bảo khách khởi động lại máy rồi gọi lại" },
        ],
        correct: ["b"],
        explain: "Xác định đúng dịch vụ + nền tảng (platform) trước, chẩn đoán đúng rồi mới xử lý.",
      },
      {
        id: "m1q3",
        type: "boolean",
        prompt: "Nên chuyển khách đến đơn vị khác ngay cả khi chưa xác định rõ nhu cầu cụ thể.",
        options: [
          { key: "t", text: "Đúng" },
          { key: "f", text: "Sai" },
        ],
        correct: ["f"],
        explain: "Sai. Phải định khung bằng 4 HỎI, xác định rõ nhu cầu trước khi quyết định chuyển.",
      },
    ],
  },
  {
    slug: "q-m2",
    title: "Quiz · Tư vấn chủ động",
    pass: 70,
    questions: [
      {
        id: "m2q1",
        type: "single",
        prompt: "Lỗi tư vấn phổ biến nhất hiện nay là gì?",
        options: [
          { key: "a", text: "Tư vấn quá kỹ làm khách chán" },
          { key: "b", text: "Thụ động, chỉ ghi nhận thông tin rồi chuyển địa bàn, không tư vấn" },
          { key: "c", text: "Nói quá nhiều về giá" },
          { key: "d", text: "Gọi lại khách quá nhiều lần" },
        ],
        correct: ["b"],
        explain: "ĐTV thụ động như \"máy ghi âm\" — chỉ xin thông tin rồi chuyển, không tư vấn sơ khởi.",
      },
      {
        id: "m2q2",
        type: "multi",
        prompt: "Kỹ năng Probing khai thác những thông tin nào trước khi chuyển?",
        options: [
          { key: "a", text: "Quy mô" },
          { key: "b", text: "Mục đích sử dụng" },
          { key: "c", text: "Hiện trạng (đã có gì chưa)" },
          { key: "d", text: "Mức độ gấp" },
        ],
        correct: ["a", "b", "c", "d"],
        explain: "Tất cả: quy mô, mục đích, hiện trạng, mức độ gấp.",
      },
      {
        id: "m2q3",
        type: "single",
        prompt: "Thứ tự đúng của khung kịch bản tư vấn chuẩn?",
        options: [
          { key: "a", text: "Chuyển địa bàn → khai thác → xác nhận" },
          { key: "b", text: "Khai thác → cung cấp cơ bản → nhận diện → xác nhận → chuyển địa bàn" },
          { key: "c", text: "Báo giá → chốt đơn → chuyển" },
          { key: "d", text: "Xác nhận → chuyển → khai thác" },
        ],
        correct: ["b"],
        explain: "Khai thác → Cung cấp cơ bản → Nhận diện → Xác nhận → Chuyển địa bàn.",
      },
    ],
  },
  {
    slug: "q-m3",
    title: "Quiz · Kiến thức Dịch vụ",
    pass: 70,
    questions: [
      {
        id: "m3q1",
        type: "single",
        prompt: "Đầu số nào MIỄN PHÍ cho người gọi (DN trả cước)?",
        options: [
          { key: "a", text: "1900" },
          { key: "b", text: "1800" },
          { key: "c", text: "Cả hai" },
          { key: "d", text: "Không số nào" },
        ],
        correct: ["b"],
        explain: "1800 miễn phí người gọi (DN trả cước); 1900 người gọi trả phí.",
      },
      {
        id: "m3q2",
        type: "single",
        prompt: "Khách cần tổng đài nội bộ để bấm số đổ về chi nhánh — tư vấn dịch vụ nào?",
        options: [
          { key: "a", text: "SMS Brandname" },
          { key: "b", text: "VCC (Tổng đài ảo)" },
          { key: "c", text: "Voice Brandname" },
          { key: "d", text: "Loa thông báo thanh toán" },
        ],
        correct: ["b"],
        explain: "VCC là tổng đài ảo: phân nhánh, định tuyến nội bộ, ghi âm.",
      },
      {
        id: "m3q3",
        type: "single",
        prompt: "Khách muốn gửi tin nhắn hiển thị TÊN thương hiệu thay số điện thoại?",
        options: [
          { key: "a", text: "SMS Brandname" },
          { key: "b", text: "Sip Trunking" },
          { key: "c", text: "eContract" },
          { key: "d", text: "1900" },
        ],
        correct: ["a"],
        explain: "SMS Brandname = tin nhắn hiển thị tên thương hiệu.",
      },
    ],
  },
  {
    slug: "q-m4",
    title: "Quiz · Giao tiếp & Đồng cảm",
    pass: 70,
    questions: [
      {
        id: "m4q1",
        type: "single",
        prompt: "Cụm từ nào giúp khách cảm nhận được sự ĐỒNG CẢM?",
        options: [
          { key: "a", text: "\"Anh chờ chút\"" },
          { key: "b", text: "\"Em hiểu ạ, em rất tiếc về sự cố…\"" },
          { key: "c", text: "\"Cái này không phải của em\"" },
          { key: "d", text: "\"Anh tự kiểm tra lại đi\"" },
        ],
        correct: ["b"],
        explain: "\"Em hiểu\", \"em rất tiếc\" thể hiện sự chia sẻ với khách.",
      },
      {
        id: "m4q2",
        type: "multi",
        prompt: "Hành vi nào là lỗi giao tiếp cần tránh?",
        options: [
          { key: "a", text: "Ngắt lời khách" },
          { key: "b", text: "Hỏi lặp lại thông tin khách đã cung cấp" },
          { key: "c", text: "Phản ứng lạnh nhạt khi khách phàn nàn" },
          { key: "d", text: "Để khách nói hết rồi mới phản hồi" },
        ],
        correct: ["a", "b", "c"],
        explain: "Ngắt lời, hỏi lặp lại, lạnh nhạt đều là lỗi. Để khách nói hết là kỹ năng tốt.",
      },
      {
        id: "m4q3",
        type: "boolean",
        prompt: "Khi cho khách chờ máy, lúc quay lại nên nói \"Cảm ơn anh/chị đã chờ máy\".",
        options: [
          { key: "t", text: "Đúng" },
          { key: "f", text: "Sai" },
        ],
        correct: ["t"],
        explain: "Đúng. Cảm ơn khi khách chờ máy là phép lịch sự cơ bản giúp khách thấy được tôn trọng.",
      },
    ],
  },
  {
    slug: "q-m5",
    title: "Quiz · Trách nhiệm & Cam kết",
    pass: 70,
    questions: [
      {
        id: "m5q1",
        type: "single",
        prompt: "Khách gọi 3–4 lần, được hứa gọi lại nhưng không ai liên hệ. Lỗi này thuộc nhóm kỹ năng nào?",
        options: [
          { key: "a", text: "Nghiệp vụ" },
          { key: "b", text: "Giao tiếp" },
          { key: "c", text: "Trách nhiệm" },
          { key: "d", text: "Kiến thức dịch vụ" },
        ],
        correct: ["c"],
        explain: "Thất hứa liên hệ lại là lỗi Tinh thần Trách nhiệm — gây mất niềm tin nghiêm trọng.",
      },
      {
        id: "m5q2",
        type: "single",
        prompt: "Khi cần hẹn trả lời, điều BẮT BUỘC phải có là gì?",
        options: [
          { key: "a", text: "Hẹn thời gian + dự kiến xử lý rõ ràng" },
          { key: "b", text: "Cúp máy nhanh" },
          { key: "c", text: "Bảo khách tự liên hệ Sale" },
          { key: "d", text: "Không cần gì thêm" },
        ],
        correct: ["a"],
        explain: "Luôn có MỐC thời gian + dự kiến rõ ràng, và đã hẹn thì phải giữ lời.",
      },
      {
        id: "m5q3",
        type: "single",
        prompt: "Khách báo lỗi, việc nên làm TRƯỚC khi nghĩ đến chuyển đơn vị khác?",
        options: [
          { key: "a", text: "Đẩy ngay sang \"các bạn Sale\"" },
          { key: "b", text: "Chủ động tra cứu trên hệ thống nội bộ" },
          { key: "c", text: "Bảo khách chờ rồi không làm gì" },
          { key: "d", text: "Hỏi lại thông tin nhiều lần" },
        ],
        correct: ["b"],
        explain: "Chủ động tra cứu trước; chỉ chuyển khi đúng phạm vi và nói rõ lý do.",
      },
    ],
  },
  {
    slug: "q-m6",
    title: "Quiz · Xử lý tình huống khó",
    pass: 70,
    questions: [
      {
        id: "m6q1",
        type: "single",
        prompt: "Khi khách căng thẳng, áp dụng công thức nào?",
        options: [
          { key: "a", text: "NGHE – NÓI – DẪN – CHỐT" },
          { key: "b", text: "3R" },
          { key: "c", text: "T.I.Ề.N" },
          { key: "d", text: "ĐÚNG – NHANH – RÕ" },
        ],
        correct: ["a"],
        explain: "NGHE – NÓI – DẪN – CHỐT: Nghe cho đủ – Nói cho rõ – Dẫn cho đúng – Chốt cho an.",
      },
      {
        id: "m6q2",
        type: "single",
        prompt: "Lỗi phụ thuộc cổng nhà nước (BHXH/Thuế), cách hẹn đúng là gì?",
        options: [
          { key: "a", text: "Hứa chắc chắn xong trong chiều nay" },
          { key: "b", text: "Đồng cảm + giải thích lỗi phụ thuộc cổng + hành động (theo dõi/thử lại sau)" },
          { key: "c", text: "Nói \"để em kiểm tra\" rồi kết thúc, không hẹn mốc" },
          { key: "d", text: "Bảo khách tự liên hệ cơ quan, không giải thích" },
        ],
        correct: ["b"],
        explain: "ĐỒNG CẢM – GIẢI THÍCH (phân định lỗi) – HÀNH ĐỘNG. Không hứa điều mình không kiểm soát được.",
      },
      {
        id: "m6q3",
        type: "single",
        prompt: "Khách chê \"giá cao quá\", cách xử lý tốt nhất?",
        options: [
          { key: "a", text: "Tranh luận chứng minh giá không cao" },
          { key: "b", text: "Đồng cảm + quy đổi giá trị + trao lựa chọn gói phù hợp" },
          { key: "c", text: "Giảm giá ngay lập tức" },
          { key: "d", text: "Bảo khách tự cân nhắc rồi cúp máy" },
        ],
        correct: ["b"],
        explain: "Không tranh luận; đồng cảm, quy về lợi ích, cho khách lựa chọn gói.",
      },
    ],
  },
];

export const quizBySlug = (slug: string) => QUIZZES.find((q) => q.slug === slug);

export const FINAL_QUIZ: Quiz = {
  slug: "final",
  title: "Bài kiểm tra nghiệp vụ (cuối khóa)",
  pass: 80,
  questions: [
    {
      id: "f1",
      type: "multi",
      prompt: "4 trụ cột kỹ năng CSKH gồm những nhóm nào?",
      options: [
        { key: "a", text: "Nghiệp vụ" },
        { key: "b", text: "Thái độ" },
        { key: "c", text: "Trách nhiệm" },
        { key: "d", text: "Giao tiếp" },
      ],
      correct: ["a", "b", "c", "d"],
      explain: "Nghiệp vụ – Thái độ – Trách nhiệm – Giao tiếp.",
    },
    {
      id: "f2",
      type: "single",
      prompt: "Lỗi tư vấn phổ biến nhất cần khắc phục?",
      options: [
        { key: "a", text: "Tư vấn quá kỹ" },
        { key: "b", text: "Chỉ ghi nhận thông tin rồi chuyển địa bàn, không tư vấn" },
        { key: "c", text: "Nói nhiều về giá" },
        { key: "d", text: "Gọi lại quá nhiều" },
      ],
      correct: ["b"],
      explain: "Thụ động, không tư vấn sơ khởi dù khách có nhu cầu rõ.",
    },
    {
      id: "f3",
      type: "single",
      prompt: "\"4 HỎI (60 giây)\" gồm những gì?",
      options: [
        { key: "a", text: "Dịch vụ gì / Ai dùng / Dùng ở đâu / Cần hỗ trợ gì" },
        { key: "b", text: "Tên / Tuổi / Địa chỉ / SĐT" },
        { key: "c", text: "Giá / Gói / Thời hạn / Khuyến mãi" },
        { key: "d", text: "Lỗi gì / Khi nào / Ở đâu / Của ai" },
      ],
      correct: ["a"],
      explain: "Dịch vụ gì / Ai dùng / Dùng ở đâu / Cần hỗ trợ gì.",
    },
    {
      id: "f4",
      type: "single",
      prompt: "Thứ tự đúng của khung kịch bản tư vấn chuẩn?",
      options: [
        { key: "a", text: "Khai thác → cung cấp cơ bản → nhận diện → xác nhận → chuyển địa bàn" },
        { key: "b", text: "Chuyển địa bàn → khai thác → xác nhận" },
        { key: "c", text: "Báo giá → chốt đơn → chuyển" },
        { key: "d", text: "Xác nhận → chuyển → khai thác" },
      ],
      correct: ["a"],
      explain: "Khai thác → Cung cấp cơ bản → Nhận diện → Xác nhận → Chuyển địa bàn.",
    },
    {
      id: "f5",
      type: "single",
      prompt: "Đầu số 1800 đặc điểm gì?",
      options: [
        { key: "a", text: "Người gọi trả phí" },
        { key: "b", text: "Miễn phí người gọi, DN trả cước" },
        { key: "c", text: "Chỉ gọi nội bộ" },
        { key: "d", text: "Là tổng đài ảo" },
      ],
      correct: ["b"],
      explain: "1800 miễn phí cho người gọi; DN chịu cước — hợp CSKH.",
    },
    {
      id: "f6",
      type: "single",
      prompt: "Khách cần nhiều kênh thoại đồng thời để nhận & gọi — tư vấn dịch vụ nào?",
      options: [
        { key: "a", text: "SMS Brandname" },
        { key: "b", text: "Sip Trunking" },
        { key: "c", text: "Loa thanh toán" },
        { key: "d", text: "eContract" },
      ],
      correct: ["b"],
      explain: "Sip Trunking = đường trung kế thoại, nhiều kênh đồng thời.",
    },
    {
      id: "f7",
      type: "single",
      prompt: "Khi khách căng thẳng, áp dụng công thức nào?",
      options: [
        { key: "a", text: "NGHE – NÓI – DẪN – CHỐT" },
        { key: "b", text: "3R" },
        { key: "c", text: "T.I.Ề.N" },
        { key: "d", text: "RÕ – ĐÚNG – AN TOÀN" },
      ],
      correct: ["a"],
      explain: "NGHE – NÓI – DẪN – CHỐT cho tình huống khách căng.",
    },
    {
      id: "f8",
      type: "single",
      prompt: "Khi cần hẹn trả lời, bắt buộc phải có?",
      options: [
        { key: "a", text: "Hẹn thời gian + dự kiến xử lý rõ ràng" },
        { key: "b", text: "Cúp máy nhanh" },
        { key: "c", text: "Bảo khách tự liên hệ Sale" },
        { key: "d", text: "Không cần gì thêm" },
      ],
      correct: ["a"],
      explain: "Phải hẹn thời gian + dự kiến rõ, và giữ lời hẹn.",
    },
    {
      id: "f9",
      type: "boolean",
      prompt: "Khách có nhu cầu rõ ràng thì được phép chỉ xin SĐT rồi chuyển địa bàn ngay.",
      options: [
        { key: "t", text: "Đúng" },
        { key: "f", text: "Sai" },
      ],
      correct: ["f"],
      explain: "Sai. Phải khai thác + cung cấp thông tin cơ bản trước, rồi mới chuyển.",
    },
    {
      id: "f10",
      type: "single",
      prompt: "Khách chê giá cao — cách xử lý đúng?",
      options: [
        { key: "a", text: "Tranh luận giá không cao" },
        { key: "b", text: "Đồng cảm + quy đổi giá trị + trao lựa chọn gói" },
        { key: "c", text: "Giảm giá ngay" },
        { key: "d", text: "Cúp máy" },
      ],
      correct: ["b"],
      explain: "Đồng cảm, quy về lợi ích, cho khách lựa chọn gói phù hợp.",
    },
  ],
};
